#!/bin/sh
#
# chkconfig: 345 57 03
# description: start nukessh
# nukessh       This shell script takes care of starting and stopping
#               nukessh
#

[ -f /usr/sbin/nukessh ] || exit 0

# Get pid file & pid

PIDFILE=/var/run/nukessh.pid

if test -f "$PIDFILE"
then
  DAEMON_PID=`cat $PIDFILE`
fi

# See how we were called.

case "$1" in
  start)
	# Start daemons.
	echo "Starting nukessh"
	/usr/sbin/nukessh -p $PIDFILE
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/nukessh
	;;
  stop)
	# Stop daemons.
        if test -n "$DAEMON_PID"
        then
          echo "Shutting down nukessh"
	  kill $DAEMON_PID
	  RETVAL=$?
          echo
          [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/nukessh
        else
          RETVAL=1
          echo
        fi

        if test -f "$PIDFILE"
        then
          rm -f $PIDFILE
        fi
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: nukessh {start|stop|restart}"
	exit 1
esac

exit $RETVAL
